config/routes.rb
Cpi::Application.routes.draw do

  root to: "home#index"

  resources :home
  resources :clients
  resources :contracts
  resources :buyers
  resources :payments
  resources :notes
  resources :reports


end

app/models/buyer.rb
class Buyer < ActiveRecord::Base
	validates		:first_name, :last_name, :address1, :city, :state,
							:zip, :country, :phone1, :payment_type,
							presence: true
end

app/models/client.rb
class Client < ActiveRecord::Base
end

app/models/contract.rb
class Contract < ActiveRecord::Base
end

app/models/home.rb
class Home < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/buyers_controller.rb
class BuyersController < ApplicationController
	def index
		@buyers = Buyer.all
	end

	def new
		@buyer = Buyer.new
	end

	def create
		@buyer = Buyer.create(buyer_params)
		if @buyer.save
			redirect_to buyers_path
		end
	end

	def edit
		@buyer = Buyer.find(params[:id])
		if @buyer.update(params[:buyer])
			redirect_to(@buyer)
		else
			render "edit"
		end
	end

	def show
		@buyer = Buyer.find_by(id: params[:id])
		if @buyer.nil?
			render buyers_path
		end
  end


	def destroy
		@buyer = Buyer.find(params[:id])
		if @buyer.destroy
			redirect_to buyers_path
		end
	end

	private

	def buyer_params
		params.require(:buyer).permit(:first_name, :middle_initial, :last_name,
																	:address1, :address2, :city, :state, :zip,
																	:country, :email, :phone1, :phone2, :fax,
																	:ssn, :payment_type)
	end
	
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
	def index
		@clients = Client.all
	end

	def new
		@client = Client.new
	end
	
	def create
		@client = Client.create(client_params)
		if @client.save
			redirect_to clients_path
		else
			render 'new'
		end
	end


	private 

	def client_params
		params.require(:client).permit(:name)
	end

end

app/controllers/contracts_controller.rb
class ContractsController < ApplicationController
	def index
		@contracts = Contract.all
	end

	def new
		@contract = Contract.new
	end
	
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	def index
	end

end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
	def index
	end
	
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
	def index
	end
	
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
	def index
	end
	
end

app/helpers/application_helper.rb
module ApplicationHelper
	

end

app/helpers/states_helper.rb
module StatesHelper
	def us_states
    [
      ['Alabama', 'AL'],
      ['Alaska', 'AK'],
      ['Arizona', 'AZ'],
      ['Arkansas', 'AR'],
      ['California', 'CA'],
      ['Colorado', 'CO'],
      ['Connecticut', 'CT'],
      ['Delaware', 'DE'],
      ['District of Columbia', 'DC'],
      ['Florida', 'FL'],
      ['Georgia', 'GA'],
      ['Hawaii', 'HI'],
      ['Idaho', 'ID'],
      ['Illinois', 'IL'],
      ['Indiana', 'IN'],
      ['Iowa', 'IA'],
      ['Kansas', 'KS'],
      ['Kentucky', 'KY'],
      ['Louisiana', 'LA'],
      ['Maine', 'ME'],
      ['Maryland', 'MD'],
      ['Massachusetts', 'MA'],
      ['Michigan', 'MI'],
      ['Minnesota', 'MN'],
      ['Mississippi', 'MS'],
      ['Missouri', 'MO'],
      ['Montana', 'MT'],
      ['Nebraska', 'NE'],
      ['Nevada', 'NV'],
      ['New Hampshire', 'NH'],
      ['New Jersey', 'NJ'],
      ['New Mexico', 'NM'],
      ['New York', 'NY'],
      ['North Carolina', 'NC'],
      ['North Dakota', 'ND'],
      ['Ohio', 'OH'],
      ['Oklahoma', 'OK'],
      ['Oregon', 'OR'],
      ['Pennsylvania', 'PA'],
      ['Puerto Rico', 'PR'],
      ['Rhode Island', 'RI'],
      ['South Carolina', 'SC'],
      ['South Dakota', 'SD'],
      ['Tennessee', 'TN'],
      ['Texas', 'TX'],
      ['Utah', 'UT'],
      ['Vermont', 'VT'],
      ['Virginia', 'VA'],
      ['Washington', 'WA'],
      ['West Virginia', 'WV'],
      ['Wisconsin', 'WI'],
      ['Wyoming', 'WY']
    ]
	end
end

app/views/buyers/index.html.erb
<h2>Buyer Browser</h2>

<div id = "search-bar">
	<%= simple_form_for buyers_path, :method => :get do |f| %>
	  <%= f.input :search, label: false, required: false, placeholder: 'ex. Byrd', class: 'pull-right' %>
	  <%= f.button :submit, "Search" %>
	<% end %>
</div>
<br>
<br>
<br>
<%= link_to "Add New", new_buyer_path, class: 'btn btn-primary' %>
<br>
<br>

<table>
  <tr>
    <th>First Name</th>
    <th>Last Name</th>
    <th>State</th>
    <th></th>
    <th></th>
  </tr>
 
	<% @buyers.each do |buyer| %>
	  <tr>
	    <td><%= buyer.first_name %></td>
	    <td><%= buyer.last_name %></td>
	    <td><%= buyer.state %></td>
	    <td><%= link_to "Show", buyer, class: 'btn btn-primary btn-sm' %></td>
	    <td><%= link_to "Update", edit_buyer_path(buyer), class: 'btn btn-primary btn-sm' %></td>
	    <td><%= link_to "Cancel", buyer, method: :delete, class: 'btn btn-primary btn-sm', 
	    				data: { confirm: "Are you sure?" } %></td>
	  </tr>
	<% end %>
</table>

app/views/buyers/new.html.erb
<h3>Enter a new Buyer</h3>
<br>
<div class="new-buyer-form">
	<%= simple_form_for(@buyer, html: {class: 'form-horizontal' }) do |f| %>
		
		<%= f.input :first_name %>
		<br>
		<%= f.input :middle_initial, length: 5 %>
		<br>
		<%= f.input :last_name %>
		<br>
		<%= f.input :address1 %>
		<br>
		<%= f.input :address2 %>
		<br>
		<%= f.input :city %>
		<br>
		<%= f.input :state %>
		<br>
		<%= f.input :zip, as: :string %>
		<br>
		<%= f.input :country, priority: [ "United States" ] %>
		<br>
		<%= f.input :email, as: :email %>
		<br>
		<%= f.input :phone1, as: :string %>
		<br>
		<%= f.input :phone2, as: :string %>
		<br>
		<%= f.input :ssn, label: "SSN#" %>
		<br>
		<%= f.input :payment_type, collection: ["EFT", "Credit Card", "Coupon Book", "Statement", "PIF"] %>
		<br>
		<%= f.submit "Create", class: 'btn btn-primary' %>
		<%= link_to "Cancel", root_path, class: 'btn btn-primary' %>
	<% end %>
	<br>
</div>

app/views/buyers/show.html.erb
<h2>Currently Editing: <%= @buyer.first_name %> <%= @buyer.last_name %></h2>

app/views/clients/index.html.erb
<h2>Client Browser</h2>

<%= simple_form_for clients_path, :method => :get do |f| %>
  <%= f.input :search, label: false, required: false, placeholder: 'ex. CPI Martial Arts' %>
  <%= f.button :submit, "Search" %>
<% end %>
<br>
<br>
<ul><% @clients.each do |client| %>
	<li><%= client.name %></li>
	<% end %>
</ul>
<br>
<%= link_to "Add New", new_client_path, class: 'btn btn-primary' %>

app/views/clients/new.html.erb
<h3>Enter a new Client</h3>
<br>
<%= simple_form_for(@client, html: {class: 'form-horizontal' }) do |f| %>
	
	<%= f.input :name %>
	<br>
	<%= f.input :owner_name %>
	<br>
	<%= f.input :address1 %>
	<br>
	<%= f.input :address2 %>
	<br>
	<%= f.input :city %>
	<br>
	<%= f.input :state %>
	<br>
	<%= f.input :zip %>
	<br>
	<%= f.input :country, priority: [ "United States" ]  %>
	<br>
	<%= f.input :email %>
	<br>
	<%= f.input :phone1 %>
	<br>
	<%= f.input :phone2 %>
	<br>
	<%= f.input :fax %>
	<br>
	<%= f.input :business_type %>
	<br>
	<%= f.input :eft_fee %>
	<%= f.input :cc_fee %>
	<%= f.input :coupon_fee %>
	<%= f.input :statement_fee %>
	<br>
	<%= f.input :username %>
	<br>
	<%= f.input :password %>
	<%= f.input :password_confirmation %>
	<br>
	<%= f.submit "Create", class: 'btn btn-primary' %>
	<%= link_to "Cancel", root_path, class: 'btn btn-primary' %>
<% end %>
<br>

app/views/contracts/index.html.erb
<h2>Contract Browser</h2>

<%= simple_form_for contracts_path, :method => :get do |f| %>
  <%= f.input :search, label: false, required: false, placeholder: 'ex. Bowman' %>
  <%= f.button :submit, "Search" %>
<% end %>
<br>
<br>
<br>
<%= link_to "Add New", new_contract_path, class: 'btn btn-primary' %>

app/views/contracts/new.html.erb
<script>
$('#datepicker').datepicker({format: 'yyyy-mm-dd'});
</script>

<h3>Enter a new Contract</h3>
<br>
<div class="new-contract-form">
	<%= simple_form_for(@contract, html: {class: 'form-horizontal' }) do |f| %>
		
		<%= f.input :programprice, label: "Program Price", as: :string %>
		<br>
		<%= f.input :downpayment, label: "Down Payment", as: :string %>
		<br>
		<%= f.input :servicefee, label: "Service Fee", as: :string %>
		<br>
		<%= f.input :totalbalance, label: "Total Balance", as: :string %>
		<br>
		<%= f.input :numberofpayments, label: "# of Payments", as: :string %>
		<br>
		<%= f.input :perpaymentamount, label: "Per Payment Amount", as: :string %>
		<br>
		<%= f.input :firstpaymentdue, label: "1st Payment Due On:", as: :string, input_html: { class: "datepicker", value: Time.now.strftime('%m/%d/%Y') } %>
		<br>
		<%= f.input :programbegins, label: "Program Begin Date", as: :string, input_html: { class: "datepicker", value: Time.now.strftime('%m/%d/%Y') }  %>
		<br>
		<%= f.input :programends, label: "Program End Date", as: :string, input_html: { class: "datepicker", value: Time.now.strftime('%m/%d/%Y') }  %>
		<br>
		<%= f.input :programdescription, label: "Program Description", as: :string %>
		<br>
		<%= f.input :latefee, label: "Late Fee Amount", as: :string %>
		<br>
		<%= f.input :graceperiod, label: "Grace Period (Days)", as: :string %>
		<br>
		<%= f.input :paymentmethod, label: "Payment Method", collection: ["EFT", "Credit Card", "Coupon Book", "Statement", "PIF"], include_blank: false %>
		<br>
		<%= f.input :member1, label: "Member #1 Name" %>
		<br>
		<%= f.submit "Create", class: 'btn btn-primary' %>
		<%= link_to "Cancel", root_path, class: 'btn btn-primary' %>
	<% end %>
	<br>
</div>

app/views/home/index.html.erb
<h2>CPI Dashboard</h2>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>

  <title>CPI | Internal App</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>

</head>


<body>

	<div class="navbar navbar-inverse navbar-fixed-top">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="/">Capital Processing</a>
      </div>
      <div class="collapse navbar-collapse">
        <ul class="nav navbar-nav">
          <li class="active"><a href="/">Home</a></li>
          <li><a href="/clients">Clients</a></li>
          <li><a href="/contracts">Contracts</a></li>
          <li><a href="/buyers">Buyers</a></li>
          <li><a href="/payments">Payments</a></li>
          <li><a href="/notes">Notes</a></li>
          <li><a href="/reports">Reports</a></li>
        </ul>
      </div><!--/.nav-collapse -->
    </div>
  </div>

  <div id="wrap">
		<div class="container">
			<%= yield %>
		</div>
	</div>

  <div id="footer">
    <div class="container">
      <p class="text-muted credit">Built by <a href="http://capital-processing.com">Capital Processing Int'l Inc.</a></p>
    </div>
  </div>

</body>
</html>

app/views/notes/index.html.erb
<h2>Notes</h2>

app/views/payments/index.html.erb
<h2>Payments</h2>

app/views/reports/index.html.erb
<h2>Reports</h2>